<a href="https://colab.research.google.com/github/siruku6/MethematicsTrial/blob/master/easily_understandable_pattern_recognition/chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# 第2章 事前確率と事後確率

## p.25

In [2]:
# -------------- 前提条件 --------------
# それぞれのコインの含有率
pi_s = np.array([0.1, 0.4, 0.5])

# それぞれのコインが表になる確率
front_probs = np.array([0.8, 0.6, 0.3])

# それぞれのコインが裏になる確率
back_probs = 1 - front_probs

# -------------- Bayesian update --------------
def bayesian_update(front_or_back_probs, prior_probs) -> np.ndarray:
    """
    ベイズ更新を1回だけ実行する関数
    """
    posterior_probs = front_or_back_probs * prior_probs / sum(front_or_back_probs * prior_probs)
    return posterior_probs


In [3]:
# 1回だけベイズ更新すると
posterior_probs = bayesian_update(front_probs, pi_s)
posterior_probs

array([0.17021277, 0.5106383 , 0.31914894])

## p.33 10回ベイズ更新する

In [4]:
posterior_probs = bayesian_update(front_probs, pi_s)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(back_probs, posterior_probs)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(back_probs, posterior_probs)
posterior_probs = bayesian_update(front_probs, posterior_probs)
posterior_probs = bayesian_update(back_probs, posterior_probs)
posterior_probs

array([0.18198217, 0.777334  , 0.04068383])

## p.34 100回ベイズ更新する

In [5]:
series_coin_toss = ["front"] * 88 + ["back"] * 12
# series_coin_toss = ["front"] * 7 + ["back"] * 3


prior_probs = pi_s

def continuous_bayesian_update(
    prior_probs: np.ndarray, series_coin_toss: list
) -> np.ndarray:

    # NOTE: 一切の試行をする前なら、試行から得られる情報が何もないため、
    #     事前確率がそのまま事後確率になる
    posterior_probs = prior_probs

    for cointoss_result in series_coin_toss:
        if cointoss_result == "front":
            probs = front_probs
        elif cointoss_result == "back":
            probs = back_probs

        posterior_probs = bayesian_update(probs, prior_probs)
        prior_probs = posterior_probs

    return posterior_probs


continuous_bayesian_update(prior_probs, series_coin_toss)

array([9.99999834e-01, 1.65886501e-07, 5.52761803e-31])

書籍p.35の値とほぼ同じ結果になった